### ISSUE TITLE
Missing vendor svg

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-providers-workflows#53]
The workflows provider needs an `app/assets/images/svg/vendor-workflows.svg` icon in [ManageIQ/manageiq-decorators](https://github.com/ManageIQ/manageiq-decorators).

I noticed this when I was viewing `Configuration > Access Control` Groups details:
![image](https://github.com/ManageIQ/manageiq-providers-workflows/assets/1637291/b04aaaf7-ce40-41ec-be82-67a854c8e197)

development.log:
```
[----] D, [2023-10-05T10:54:31.885764 #19901:644ec] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 2, in use: 0, waiting_in_queue: 0
[----] I, [2023-10-05T10:54:31.926761 #19901:644ec]  INFO -- : Started GET "/images/svg/vendor-workflows.svg" for 127.0.0.1 at 2023-10-05 10:54:31 -0500
[----] F, [2023-10-05T10:54:31.986796 #19901:644ec] FATAL -- :   
ActionController::RoutingError (No route matches [GET] "/images/svg/vendor-workflows.svg"):
  
actionpack (6.1.7.6) lib/action_dispatch/middleware/debug_exceptions.rb:33:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7.6) lib/rails/rack/logger.rb:28:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.8) lib/rack/method_override.rb:24:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
secure_headers (3.9.0) lib/secure_headers/middleware.rb:12:in `call'
railties (6.1.7.6) lib/rails/engine.rb:539:in `call'
railties (6.1.7.6) lib/rails/railtie.rb:207:in `public_send'
railties (6.1.7.6) lib/rails/railtie.rb:207:in `method_missing'
puma (6.4.0) lib/puma/configuration.rb:272:in `call'
puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
puma (6.4.0) lib/puma/server.rb:443:in `process_client'
puma (6.4.0) lib/puma/server.rb:241:in `block in run'
puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by kbrock** [comment]
@agrare do you have a `/images/svg/vendor-workflows.svg`

**Comment by agrare** [comment]
Oh no we don't, I think we can link this to the MIQ image for now I'm not sure I want to use Amazon's logo since states-language is a separate thing from Amazon Step Functions :tm: 
@Fryguy thoughts?

**Comment by Fryguy** [comment]
There is a simple workflow like image - let me find it.

**Comment by Fryguy** [comment]
I was thinking of something like this from [Carbon](https://carbondesignsystem.com/guidelines/icons/library/)

<img src="https://github.com/ManageIQ/manageiq-providers-workflows/assets/52120/116a4722-61d1-4ff1-b9a8-74eb27d8521f" data-canonical-src="https://github.com/ManageIQ/manageiq-providers-workflows/assets/52120/116a4722-61d1-4ff1-b9a8-74eb27d8521f" width="32" />
